FROM jenkins/jenkins:lts

#Install plugin if necessary
{% if jenkins_plugins|length > 0 %}
RUN /usr/local/bin/install-plugins.sh {% for plugin in jenkins_plugins %}{{ plugin }} {% endfor %}
{% endif %}

#install tools with root
USER root
RUN apt-get update && \
apt-get -y install apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common && \
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable" && \
apt-get update && \
apt-get -y install docker-ce

#give the jenkins user sudo privileges in order to be able to run Docker commands inside the container
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
 

#drop back to the jenkins user
USER jenkins
