- name: Installing from the APT repository(install Kibana)
  apt:
    name: kibana
    state: present
  become: yes

- name: Start service kibana, if not running
  service:
    name: kibana
    state: started
    enabled: yes

- name: check if kibana {{ kibana_port }} can be access
  uri:
    url: http://127.0.0.1:{{ kibana_port }}
  register: result
  until: (result.status == 200)
  retries: "{{ web_connection_retries }}"
  delay: "{{ web_connection_delay }}"
