---
- hosts: efk
  roles:
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
      oracle_java_version: 8
    - role: es-kibana
    - { role: fluentd, tags: [ 'fluentd', 'fluentd-server' ] }


- hosts: fluentd-client
  roles:
    - { role: fluentd, tags: [ 'fluentd', 'fluentd-client' ] }
