---
- hosts: all
  roles:
    - role: geerlingguy.java
      vars:
        java_packages: openjdk-8-jdk
    - role: efk-fluentd

  pre_tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

    - name: apt-get update
      apt:
        update_cache: yes
