---
- hosts: efk
  roles:
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
      oracle_java_version: 8
      become: yes
    - role: es-kibana
      become: yes
    - role: fluentd
      es_server: localhost


- hosts: ~.*fluentd-client
  roles:
    - role: fluentd
      fluentd_server: 192.168.34.115
