---
- hosts: efk
  roles:
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
      oracle_java_version: 8
    - role: efk-fluentd

- hosts: fluentd-client
  roles:
    - { role: efk-fluentd, tags: [ 'fluentd-client' ] }
