---
- hosts: all
  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: geerlingguy.java
      vars:
        java_packages: "{{ java_packages }}"

  tasks:
    - name: Ensure denpendencies
      pip:
        name: docker-py

  pre_tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

    - name: apt-get update
      apt:
        update_cache: yes
