---

- hosts: all
  become: yes
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
  tasks:
    - name: Ensure denpendencies
      pip:
        name: docker-py
    - name: Add the user 'vagrant' with a group of 'docker'
      user:
        name: vagrant
        group: docker

- hosts: all
  roles:
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
      oracle_java_version: 8
