---
- hosts: all
  become: yes
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
  tasks:
    - name: Ensure denpendencies
      pip:
        name: docker-py
    - name: Add the user 'vagrant' with a group of 'docker'
      user:
        name: vagrant
        group: docker

- hosts: jenkins_server
  become: yes
  tags: git-crypt
  tasks:
    - name: Ensure dependenies is installed
      apt:
        name:
          - make 
          - g++
          - libssl-dev
        state: present
    - name: clone git-crypt
      git: 
        repo: 'https://github.com/AGWA/git-crypt.git'
        dest: /tmp/git-crypt/checkout
    - name: make && make install
      shell: 'cd /tmp/git-crypt/checkout; make && make install'
 
