---
- hosts: all
  tasks:
    - name: git clone and gradle.
      git:
      repo: https://github.com/lolspider/hello-docker-world.git
      dest: /svr/checkout/

    - name: create docker image
      shell: ./gradlew build docker
      chdir: /svr/checkout/

    - name: tag image
      shell: docker tag lolspider/hello-docker-world:latest lolspider/hello-docker-world:{{ tagversion }}

    - name: push image
      docker_image:
        name: lolspider/hello-docker-world:{{ tagversion }}
        push: yes
