---
- hosts: jenkins_server
  roles:
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
      oracle_java_version: 8
    - role: geerlingguy.jenkins
      jenkins_plugins:
        - Pipeline
        - "Docker Pipeline"
        - "Pipeline: Stage View"
        - GitHub
        - Git
        - ansible
  tasks:
    - name: Add the user 'jenkins' with a group of 'docker'
      tags: jenkins-docker
      user:
        name: jenkins
        group: docker
  become: yes
