---
- hosts: jenkins_server
  pre_tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'
    - name: apt-get update
      apt:
        update_cache: yes

- hosts: jenkins_server
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages: openjdk-8-jdk
    - role: geerlingguy.jenkins
  become: true
