---
- hosts: all
  tasks:
    - name: create a spring-boot container.
      docker_container:
        name: spring-boot
        image: springio/gs-spring-boot-docker:{{ spring_boot_version }}
        state: started
        pull: yes
        ports:
          - "{{ guest_port }}:{{ host_port }}"

    - name: check if web can be access
      uri:
        url: http://{{ ansible_hostname }}:{{ guest_port }}
      register: result
      until: (result.status == 200)
      retries: "{{ web_connection_retries }}"
      delay: "{{ web_connection_delay }}"
