---
- hosts: all
  tasks:
    - name: pull image
      docker_container:
        name: hello-docker-world
        image: lolspider/hello-docker-world:{{ tagversion }}
        log_driver: fluentd
        log_options:
          fluentd-address: localhost:24224
          tag: "{{ docker_tagenv }}:lolspider/hello-docker-world:{{ tagversion }}"
        ports:
          - "{{ guest_port }}:{{ host_port }}"
        state: started

    - name: check if web can be access
      uri:
        url: http://{{ ansible_hostname }}:{{ guest_port }}
      register: result
      until: (result.status == 200)
      retries: "{{ web_connection_retries }}"
      delay: "{{ web_connection_delay }}"
