---
- hosts: all
  tasks:
    - name: pull docker image
      docker_container:
        name: hello-docker-world
        image: lolspider/hello-docker-world:{{ tagversion }}
        state: started
        ports:
          - "{{ guest_port }}:{{ host_port }}"
