---
- name: Installing Fluentd
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent3.sh | sh

- name: install elasticsearch output plugin
  shell: td-agent-gem install fluent-plugin-elasticsearch
  notify:
    - restart fluentd
