---
- name: Installing Fluentd
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent3.sh | sh

- name: install elasticsearch output plugin
  shell: td-agent-gem install fluent-plugin-elasticsearch
  notify:
    - restart fluentd

# homework: move to handler
- name: Check if port {{ fluentd_port }} is listening
  wait_for:
    port: "{{ fluentd_port }}"
    delay: "{{ tcp_delay_time }}"
    timeout: "{{ tcp_timeout }}"
    msg: "Timeout waiting for {{ fluentd_port }} to respond"
