---
- include_tasks: install-fluentd.yml

- name: copy configuration to fluentd server
  template:
    src: fluentd-server.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: "{{ user }}"
  become: yes
  notify:
    - restart fluentd
  when: es_server is defined

- name: copy configuration to fluentd client
  template:
    src: fluentd-client.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: "{{ user }}"
  become: yes
  notify:
    - restart fluentd
  when: fluentd_server is defined
