---
- name: restart fluentd
  service:
    name: td-agent
    state: restarted
  become: yes

- name: Check if fluentd port is listening
  listen: restart fluentd
  wait_for:
    port: "{{ fluentd_port }}"
    delay: "{{ tcp_delay_time }}"
    timeout: "{{ tcp_timeout }}"
    msg: "Timeout waiting for {{ fluentd_port }} to respond"
