pipeline {
    agent any
    stages {
        stage("install docker or jdk") {
            steps {
                script {
                    sh 'ansible-playbook -i $inventory --extra-vars "is_docker=$is_docker is_jdk=$is_jdk jdk-version=${jdk-version}" -u vagrant -b environment.yml'
                }
            }
        }
    }
}
