---
- name: config staging/prod fluentd
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: "{{ user }}"
  tags:
    - fluentd-client

- name: install elasticsearch output plugin
  shell: td-agent-gem install fluent-plugin-elasticsearch
  tags:
    - fluentd-client
