---

- include_tasks: install-es.yml

- include_tasks: install-kibana.yml

- include_tasks: install-fluentd.yml

- name: copy configuration to fluentd server
  tags:
    - fluentd-server
  template:
    src: td-agent.conf.server.j2
    dest: /etc/td-agent/td-agent.conf
    owner: "{{ user }}"
  notify:
    - restart fluentd

- name: copy configuration to fluentd client
  tags:
    - fluentd-client
  template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: "{{ user }}"
  notify:
    - restart fluentd

