---

- name: Include variables
  include_vars: Debian.yml

- include_tasks: setup-elastic-repo.yml

- name: Installing from the APT repository(install Elasticsearch)
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Check if port 9200 is listening
  wait_for:
    port: 9200
    delay: 5
    timeout: 50
    msg: "Timeout waiting for 9200 to respond"

- name: Installing from the APT repository(install Kibana)
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: check if kibana can be access
  uri:
    url: http://{{ ansible_hostname }}:5601
  register: result
  until: (result.status == 200)
  retries: "{{ web_connection_retries }}"
  delay: "{{ web_connection_delay }}"

- name: Installing Fluentd
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent3.sh | sh
  tags:
    - fluentd

- include_tasks: config-fluentd.yml 
  tags:
    - fluentd

- name: copy configuration to fluentd_server
  copy:
    src: td-agent.conf.server
    dest: /etc/td-agent/td-agent.conf
    owner: vagrant
    mode: 0644

- name: Ensure Fluentd is started
  service: 
    name: td-agent
    state: started
  tags:
    - fluentd

- name: Check if port 24224 is listening
  wait_for:
    port: 24224
    delay: 5
    timeout: 30
    msg: "Timeout waiting for 24224 to respond"
  tags:
    - fluentd
